name: ml-md-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.25.2
  - scipy=1.9.3
  - matplotlib
  - ase
  - pandas
  - cmake
  - make
  - pip
  - tqdm
  - pip:
      - tensorflow==2.9.1




