name: ml-md-env2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.25.2             # Compatible con SciPy y TensorFlow 2.9.1
  - scipy=1.9.3              # Evita errores de GLIBCXX
  - matplotlib               # Visualización
  - ase                      # Manipulación de estructuras atómicas
  - cmake                    # Necesario para compilar deepmd-kit
  - make                     # Utilidad de compilación
  - pip
  - pip:
      - tensorflow==2.9.1            # Estable y compatible con compilación
      - deepmd-kit --no-binary deepmd-kit
      - dpdata

